# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- demo/*
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
#twitter:
#  username: DavidDarnes # jekyll-seo-tag > Owners twitter username"
author: jcneivaa # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Camilo Neiva # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.facebook.com/camylo.neiva
    - https://github.com/jcneivaa

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Proyectos # Needed for Siteleaf
    output: true
    description: "Un poco de mi trabajo y proyectos actuales." # The post list page content
    feature_image: "http://i.imgur.com/olzzfAW.png"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Jcneivaa" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Shalalalalalalala" # Site description and default description, also used in jekyll-seo-tag
url: "https://jcneivaa.github.io/" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/jcneivaa/jcneivaa.github.io"
email: "jcneivaa@unal.edu.co"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "https://s.gravatar.com/avatar/0cf1cb4c1be5f2fda5597a8fa88ef9e7?s=80" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# 8. Site navigation
navigation_header:
  Home: /
#  Elements: /elements/
  Proyectos: /blog/
#  Categories: /categories/
#  Search: /search/
#  Fork Alembic: https://github.com/daviddarnes/alembic

navigation_footer:
  Proyectos: /blog/

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
#  Twitter: https://twitter.com/DavidDarnes
#  LinkedIn: https://www.linkedin.com/in/daviddarnes
#  Google+: https://plus.google.com/+DavidDarnes
#  GitHub: https://github.com/daviddarnes
#  link: https://darn.es
#  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
#  Twitter: "#1DA1F2"
#  facebook: "#3B5998"
#  Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""
